### ISSUE TITLE
ascii_armor field too small on MySQL

### ISSUE THREAD

**Issue by adarobin** [valentindeaconu/terralist#109]
The `ascii_armor` field in the `authority_keys` table is only 256 characters on MySQL. This is problematic since the ascii armor is thousands of characters. I was able to add the same ascii armor when using the sqlite backend.

```
mysql> describe authority_keys;
+-----------------+--------------+------+-----+---------+-------+
| Field           | Type         | Null | Key | Default | Extra |
+-----------------+--------------+------+-----+---------+-------+
| id              | varchar(256) | NO   | PRI | NULL    |       |
| created_at      | datetime     | YES  |     | NULL    |       |
| updated_at      | datetime     | YES  |     | NULL    |       |
| authority_id    | varchar(256) | YES  | MUL | NULL    |       |
| key_id          | varchar(256) | NO   |     | NULL    |       |
| ascii_armor     | varchar(256) | NO   |     | NULL    |       |
| trust_signature | varchar(256) | NO   |     | NULL    |       |
+-----------------+--------------+------+-----+---------+-------+
7 rows in set (0.01 sec)
```

No error is returned when I attempt to add a key in the web interface, but the key is not added. I can see the insert statement in the debug log.

```
{"level":"debug","elapsed_ms":2.13922,"sql":"INSERT INTO `authority_keys` (`created_at`,`updated_at`,`authority_id`,`key_id`,`ascii_armor`,`trust_signature`,`id`) VALUES ('2023-01-30 20:05:54.095','2023-01-30 20:05:54.095','588d1db6-b6b0-4406-b69c-fdcc10c6b25e','596415EE2E6E3A55','-----BEGIN PGP PUBLIC KEY BLOCK-----truncated for clarity-----END PGP PUBLIC KEY BLOCK-----','596415EE2E6E3A55','3e6d198c-1c38-4362-ad8b-185f45c72b8e') ON DUPLICATE KEY UPDATE `authority_id`=VALUES(`authority_id`)","rows":0,"time":"2023-01-30T20:05:54Z"}
{"level":"debug","elapsed_ms":27.815923,"sql":"UPDATE `authorities` SET `created_at`='2023-01-30 20:02:28',`updated_at`='2023-01-30 20:05:54.093',`name`='umich-vci',`policy_url`='https://redacted',`owner`='adarobin@umich.edu' WHERE `id` = '588d1db6-b6b0-4406-b69c-fdcc10c6b25e'","rows":1,"time":"2023-01-30T20:05:54Z"}
{"level":"info","method":"POST","path":"/authority/588d1db6-b6b0-4406-b69c-fdcc10c6b25e/keys/add","resp_time":41.430827,"status":302,"client_ip":"redacted","time":"2023-01-30T20:05:54Z"}
```

If I copy the SQL statement and run it directly on the MySQL server I receive the message:
```
ERROR 1406 (22001): Data too long for column 'ascii_armor' at row 1
```

**Comment by adarobin** [comment]
I messed with the DB schema and I was able to get it to start working, but I'm not really sure the optimal size/type for this field

```
mysql> alter table authority_keys modify column ascii_armor TEXT;
Query OK, 0 rows affected (0.41 sec)
```

**Comment by adarobin** [comment]
I _think_ this line needs to be changed https://github.com/valentindeaconu/terralist/blob/94540844d3e39a44f9dd66cbc1c62938311c4bc5/internal/server/models/authority/key.go#L13 but I don't have time to test at the present moment.

Something like this - 

```
	AsciiArmor     string `gorm:"not null;size:65535"`
```

**Comment by adarobin** [comment]
You could comment out this line https://github.com/valentindeaconu/terralist/blob/94540844d3e39a44f9dd66cbc1c62938311c4bc5/pkg/database/mysql/creator.go#L33 which would result in every string being treated as longtext (up to 4 GB) in MySQL which is probably way too big.

You could also change it to something like 4096, but again every string would be made that size in the database.

**Comment by valentindeaconu** [comment]
Hello!

Thank you for this issue submission.

In my opinion, this problem should be fixed by increasing the size of the AsciiArmor attribute. Expanding all string sizes will just allocate a lot of unused memory.

I will investigate both using the gorm's `size` attribute and implementing a custom data driver which changes the type depending on the database. I hope to come up with a fix by the end of this week.

Hopefully, in the near future, the tests will catch those errors.
