### ISSUE TITLE
Use API Key to login?

### ISSUE THREAD

**Issue by adarobin** [valentindeaconu/terralist#117]
Is it possible to use an API Key to generate a login token?

I have terraform code running through Scalr that needs to be able to download a provider from the registry like in [this example](https://www.scalr.com/blog/credential-helper). It would be nice to be able to use an API key in a [Credential Helper](https://developer.hashicorp.com/terraform/internals/credentials-helpers) to get a login token to download from the provider registry.

My current workaround is to copy my token after I run `terraform login myregistry.example.com` and set an environment variable `TF_TOKEN_myregistry_example_com` but that isn't a sustainable process.

**Comment by valentindeaconu** [comment]
Terralist supports API keys.

To obtain one, you have to log in to its web interface using your IdP, then create a namespace (authority) and then add a public GPG key for that authority. When the authority is set up, you can create an API key, which will generate a UUID.

Then, all you have to do is to put the API key into the `credentials.tfrc.json`, prefixed with `x-api-key:` (resulting in something like `x-api-key:<api-key-uuid>`.

See [Getting Started](https://github.com/valentindeaconu/terralist/blob/master/docs/GETTING-STARTED.md#how-to-use-it) for some examples of how you can use the API.

I don't have experience with Scalr, but if you say it works by copying the token from the `terraform login` command, then you should set the `x-api-key:<uuid>` to `TF_TOKEN_myregistry_example_com`.

**Comment by adarobin** [comment]
Ahh I see, not sure why I didn't think to try that.  I only tried `<api-key-uuid>` and not `x-api-key:<api-key-uuid>` even though that is what I was using with `curl` when I was adding a provider.
