### ISSUE TITLE
Problem uploading a new module to registry

### ISSUE THREAD

**Issue by jsidney** [valentindeaconu/terralist#124]
Hi guys. im probably doing something stupid... 
i deployed terralist to a simple AWS fargate cluster and am using postgres as the db and s3 as the module storage. 
i am trying to upload a new module to test all of my permissions etc and this is my curl command:
```sh
curl -X POST https://terralist.synth-platform.co.za/v1/api/modules/fargate-application/aws/1.0.0/upload \
     -H "Authorization: Bearer x-api-key:xxxxxxxxxxxxxxx" \
     -d '{ "download_url": "fargate-application-aws-1.0.0.tgz" }'
```
and this is the error I am getting:
```
{"errors":["download failure: stat /tmp/tl-fetch2148234323/fargate-application-aws-1.0.0: no such file or directory"]}%
```

I have the `tar` archive in the same directory that I am running the curl command from..... can someone help me with what I am doing wrong?

**Comment by valentindeaconu** [comment]
Hello!

You're asking Terralist's server to download the file `fargate-application-aws-1.0.0.tgz` from its current working directory (since that is a relative path) and Terralist responds with "no such file or directory", because there probably isn't. 

I guess, what you want to do is to upload the `fargate-application-aws-1.0.0.tgz` file from your CWD into the remote Terralist server. In order to do such, you have to upload the file somewhere and pass the download URL to Terralist. Terralist has to download the file from somewhere and then upload it to its storage system.

Uploading files directly into Terralist is not yet supported (check #33).

**Comment by jsidney** [comment]
gotcha. so just to play it back to you -  if I upload the file to the s3 bucket that terralist uses, then use that download URL to tell terralist where the module is stored?

**Comment by jsidney** [comment]
thanks for the options that you suggested. my use case is to upload a new version as part of a ci/cd process (from bitbucket-pipelines etc). the problem I'm running into is that the docker image doesn't have GIT in the image (not a big deal in the big picture but it would be nice to not have to have a big docker image as well as fiddling with ssh keys etc). i tried to upload the module to s3 and then pull from there, but terralist is getting an error 409 in the logs. 
just curious what approaches you have had success with?
```
{"level":"warn","method":"POST","path":"/v1/api/modules/fargate-application/aws/1.0.0/upload","resp_time":36.409422,"status":409,"client_ip":"105.27.203.230","time":"2023-02-16T09:44:10Z"}
```

**Comment by valentindeaconu** [comment]
I guess the 409 response is returned by the S3 resolver. Did you upload the file in the same location as Terralist would normally do?

> the problem I'm running into is that the docker image doesn't have GIT in the image

This looks like a bug, Terralist should be able to use all `go-getter` protocols, which means it should be bundled with git, mercurial, aws-cli and gcloud, even at the cost of increasing the image size.

> just curious what approaches you have had success with?

I only tested it with local paths and git on my dev environment and with git and http on the deployed server.

**Comment by jsidney** [comment]
hmm.... this is weird. 
definitely something to look into. 
I am going to carry on debugging this weird 409 error. currently, my `log-level` is set to `debug`..... just so I know is there a more verbose option?

**Comment by jsidney** [comment]
@valentindeaconu  - dont stress.... it kinda helps when you follow the instructions for `go-getter` 😆 .... 
you have to prepend `s3::` to the URL 
(now I'm getting a standard access denied error)

**Comment by jsidney** [comment]
@valentindeaconu  - i am going to close this task. i managed to get it working. 
i might just open another PR when i get a moment to just add some more info in the docs about how to specify the URLs etc (ie: how to use `go-getter`)
