### ISSUE TITLE
Compile error on macOS 13

### ISSUE THREAD

**Issue by harry-xm** [valentindeaconu/terralist#138]
The '-Wno-return-local-addr' option in CGO_CFLAGS from Taskfile.yaml is not valid on macOS 13.

```
runtime/cgo
# runtime/cgo
error: unknown warning option '-Wno-return-local-addr'; did you mean '-Wno-return-stack-address'? [-Werror,-Wunknown-warning-option]
```

Terralist commit: 0e7bfef86a9715e86c316b9a97a03d51e1d80685

**Comment by valentindeaconu** [comment]
I believe the default C compiler on macOS (clang) does not support that flag. Can you try to remove [the `CGO_CFLAGS` from the `Taskfile.yaml` file](https://github.com/valentindeaconu/terralist/blob/master/Taskfile.yaml#L20-L22)? I have set them to get rid of some annoying C warnings while building the SQLite library.
