### ISSUE TITLE
Bug: existing module new version upload always return "version already exists" error

### ISSUE THREAD

**Issue by vincentgna** [valentindeaconu/terralist#35]
How to reproduce:

1. Upload module (i.e. `default/foo/aws/1.0.0/upload`)
1. Upload another version (i.e. `default/foo/aws/1.0.1/upload`)

Response: 409 - `version 1.0.1 already exists`
Expected: 200 - no errors

**Comment by vincentgna** [comment]
https://github.com/valentindeaconu/terralist/blob/661f9ab0830c48f73cf650c275ff323387b03716/internal/server/repositories/module.go#L114

should use the retrieved `m` versions (`m.Versions`) rather than function argument `n`

**Comment by valentindeaconu** [comment]
Thanks for finding this! Hello! I also found it during the #34 ([here](https://github.com/valentindeaconu/terralist/pull/34/files#diff-fbef553a1e012c027a8094e789d1dcf33f573ad6992718ab22ef353b2a655601L114-R149)). I will merge your PR to fix it before the breaking-change enters.
